package com.homira.aod;

import android.app.*;
import android.content.*;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.os.*;
import android.provider.Settings;
import android.view.*;
import android.widget.*;
import java.time.*;
import java.util.*;
import java.io.*;
import java.util.concurrent.*;

public final class MainActivity extends Activity {
    public Store store;public Surface canvas;public Domain.History history=new Domain.History();public String screen="Home";
    private LinearLayout root,bar,contextBar;private TextView title;private final ExecutorService io=Executors.newSingleThreadExecutor();private String pendingImage="",pendingExport="";private Dialog sheet;
    @Override public void onCreate(Bundle state){super.onCreate(state);try{store=new Store(this);}catch(Exception e){LinearLayout failed=Ui.column(this);failed.addView(Ui.text(this,"Your designs couldn't be opened. Your saved file is preserved.",18,Ui.TEXT));setContentView(failed);return;}
        if(state!=null){pendingImage=state.getString("image","");pendingExport=state.getString("export","");String page=state.getString("screen","Home");if(page.equals("Studio")){studio(store.find(state.getString("theme",store.active)));return;}if(page.equals("Schedules")){schedules();return;}if(page.equals("Settings")){settings();return;}}home();}
    @Override protected void onSaveInstanceState(Bundle state){super.onSaveInstanceState(state);state.putString("screen",screen);state.putString("theme",canvas==null?store.active:canvas.theme.id);state.putString("image",pendingImage);state.putString("export",pendingExport);}
    @Override protected void onResume(){super.onResume();if(store!=null&&screen.equals("Settings"))settings();}
    private void shell(String label,boolean back){root=Ui.column(this);root.setBackgroundColor(Ui.BG);root.setOnApplyWindowInsetsListener((v,insets)->{v.setPadding(insets.getSystemWindowInsetLeft(),insets.getSystemWindowInsetTop(),insets.getSystemWindowInsetRight(),insets.getSystemWindowInsetBottom());return insets;});setContentView(root);root.requestApplyInsets();bar=Ui.row(this);if(back)bar.addView(Ui.icon(this,"Back",this::home));title=Ui.text(this,label,20,Ui.TEXT);title.setTypeface(null,android.graphics.Typeface.BOLD);bar.addView(title,new LinearLayout.LayoutParams(0,Ui.dp(this,56),1));root.addView(bar);canvas=null;}
    private void toast(String value){Toast.makeText(this,value,Toast.LENGTH_SHORT).show();}
    private void error(Exception e){toast(e.getMessage()==null?"Couldn't complete that action.":e.getMessage());}
    private void persist(){try{store.put(canvas.theme);}catch(Exception e){error(e);}canvas.invalidate();contextControls();}
    private void change(Runnable edit){Domain.Theme before=canvas.theme.copy();edit.run();history.record(before);persist();}
    public void home(){screen="Home";shell("AOD",false);bar.addView(Ui.icon(this,"Schedules",this::schedules));bar.addView(Ui.icon(this,"Settings",this::settings));bar.addView(Ui.icon(this,"Add",this::newDesign));
        ScrollView scroll=new ScrollView(this);LinearLayout list=Ui.column(this);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));
        Domain.Theme current=store.current(isCharging());Domain.Rule rule=store.override?null:Domain.resolve(store.rules,ZonedDateTime.now(),isCharging());list.addView(Ui.text(this,rule==null?(store.override?"Manual · ":"Current · ")+current.name:rule.name+" · "+current.name,14,Ui.ACCENT));
        for(Domain.Theme t:store.themes){LinearLayout card=Ui.column(this);card.setBackground(Ui.rounded(Ui.PANEL,Ui.dp(this,16)));LinearLayout.LayoutParams cp=new LinearLayout.LayoutParams(-1,-2);cp.setMargins(Ui.dp(this,16),Ui.dp(this,8),Ui.dp(this,16),Ui.dp(this,8));list.addView(card,cp);
            Surface preview=new Surface(this,t);preview.shift=false;preview.setContentDescription(t.name+" design preview");card.addView(preview,new LinearLayout.LayoutParams(-1,Ui.dp(this,220)));preview.setOnClickListener(v->studio(t));
            LinearLayout row=Ui.row(this);row.addView(Ui.text(this,t.name,17,Ui.TEXT),new LinearLayout.LayoutParams(0,-2,1));row.addView(Ui.button(this,"Edit",()->studio(t)));row.addView(Ui.icon(this,"Preview",()->preview(t,"Preview")));row.addView(Ui.icon(this,"More",()->designMenu(t)));card.addView(row);}
        LinearLayout bottom=Ui.row(this);bottom.addView(Ui.button(this,"Use display",this::modes),new LinearLayout.LayoutParams(0,-2,1));bottom.addView(Ui.button(this,"Import theme",this::importTheme),new LinearLayout.LayoutParams(0,-2,1));root.addView(bottom);
        if(!store.settings().getBoolean("welcomed",false)){store.settings().edit().putBoolean("welcomed",true).commit();new AlertDialog.Builder(this).setTitle("Make space for your time").setMessage("Edit a design, then choose Preview, bedside Charging or your device's Ambient screensaver. Notification access is optional.").setPositiveButton("Start designing",(d,w)->studio(store.find(store.active))).setNegativeButton("Explore",null).show();}}
    private boolean isCharging(){Intent i=registerReceiver(null,new IntentFilter(Intent.ACTION_BATTERY_CHANGED));return i!=null&&i.getIntExtra(BatteryManager.EXTRA_PLUGGED,0)!=0;}
    private void designMenu(Domain.Theme t){new AlertDialog.Builder(this).setTitle(t.name).setItems(new String[]{"Use this design","Rename","Duplicate","Export theme","Delete"},(d,w)->{switch(w){case 0:store.active=t.id;store.override=true;store.save();home();break;case 1:input("Design name",t.name,value->{t.name=value.trim();try{store.put(t);home();}catch(Exception e){error(e);}});break;case 2:Domain.Theme c=t.copy();c.id=UUID.randomUUID().toString();c.name=t.name+" copy";store.put(c);home();break;case 3:exportTheme(t);break;case 4:if(store.themes.size()==1){toast("Keep at least one design.");return;}new AlertDialog.Builder(this).setTitle("Delete "+t.name+"?").setMessage("This also removes schedules using this design.").setPositiveButton("Delete",(q,k)->{store.themes.remove(t);store.rules.removeIf(r->r.themeId.equals(t.id));if(store.active.equals(t.id))store.active=store.themes.get(0).id;store.save();home();}).setNegativeButton("Cancel",null).show();break;}}).show();}
    private void newDesign(){input("Design name","My AOD",name->{Domain.Theme t=new Domain.Theme();t.name=name.trim();Domain.Element e=new Domain.Element();t.elements.add(e);try{store.put(t);studio(t);}catch(Exception ex){error(ex);}});}
    private void input(String label,String value,java.util.function.Consumer<String> done){EditText edit=new EditText(this);edit.setText(value);edit.setSingleLine();edit.setSelectAllOnFocus(true);AlertDialog dialog=new AlertDialog.Builder(this).setTitle(label).setView(edit).setPositiveButton("Save",null).setNegativeButton("Cancel",null).create();dialog.setOnShowListener(v->dialog.getButton(-1).setOnClickListener(b->{if(edit.getText().toString().trim().isEmpty()){edit.setError("Enter a value");return;}done.accept(edit.getText().toString());dialog.dismiss();}));dialog.show();}
    public void studio(Domain.Theme t){screen="Studio";history=new Domain.History();shell(t.name,true);bar.addView(Ui.icon(this,"Undo",()->{canvas.theme=history.undo(canvas.theme);persist();}));bar.addView(Ui.icon(this,"Redo",()->{canvas.theme=history.redo(canvas.theme);persist();}));bar.addView(Ui.icon(this,"Preview",()->preview(canvas.theme,"Preview")));
        canvas=new Surface(this,t.copy());canvas.editing=true;canvas.shift=false;canvas.edits=new Surface.EditListener(){public void selected(String id){contextControls();}public void changed(Domain.Theme before){history.record(before);persist();}};root.addView(canvas,new LinearLayout.LayoutParams(-1,0,1));contextBar=Ui.row(this);root.addView(contextBar);contextControls();}
    private void contextControls(){if(contextBar==null||canvas==null||!screen.equals("Studio"))return;contextBar.removeAllViews();contextBar.addView(Ui.icon(this,"Add",this::addMenu));contextBar.addView(Ui.icon(this,"Layers",this::layers));Domain.Element e=canvas.selection();if(e!=null){contextBar.addView(Ui.button(this,e.type,this::inspector),new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));contextBar.addView(Ui.icon(this,"More",()->elementMenu(e)));}else{contextBar.addView(Ui.button(this,"Canvas style",this::canvasStyle),new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));}bar.getChildAt(2).setEnabled(history.canUndo());bar.getChildAt(3).setEnabled(history.canRedo());}
    public void add(String type){change(()->{Domain.Element e=new Domain.Element();e.type=type;e.y=320;e.size=type.equals("Clock")?52:18;e.h=type.equals("Clock")?90:64;if(type.equals("Shape")){e.family="Rectangle";e.h=40;}canvas.theme.elements.add(e);canvas.selected=e.id;});if(type.equals("Calendar")&&checkSelfPermission(android.Manifest.permission.READ_CALENDAR)!=PackageManager.PERMISSION_GRANTED)new AlertDialog.Builder(this).setTitle("Calendar on your display").setMessage("Allow access to show your next event. Event titles stay hidden on ambient displays unless enabled in Privacy.").setPositiveButton("Allow",(d,w)->requestPermissions(new String[]{android.Manifest.permission.READ_CALENDAR},40)).setNegativeButton("Later",null).show();if(type.equals("Notifications")||type.equals("Media"))if(!Notifications.granted(this))notificationAccess();if(type.equals("Image"))chooseImage(canvas.selected);}
    private void addMenu(){new AlertDialog.Builder(this).setTitle("Add element").setItems(Domain.TYPES,(d,w)->add(Domain.TYPES[w])).show();}
    private void layers(){String[] values=new String[canvas.theme.elements.size()];for(int i=0;i<values.length;i++){Domain.Element e=canvas.theme.elements.get(i);values[i]=(i+1)+" · "+e.type+(e.locked?" · locked":"")+(!e.visible?" · hidden":"");}new AlertDialog.Builder(this).setTitle("Layers · back to front").setItems(values,(d,w)->{canvas.selected=canvas.theme.elements.get(w).id;canvas.invalidate();contextControls();inspector();}).show();}
    private void elementMenu(Domain.Element e){new AlertDialog.Builder(this).setTitle(e.type).setItems(new String[]{"Duplicate","Delete",e.locked?"Unlock":"Lock",e.visible?"Hide":"Show","Bring forward","Send backward","Center horizontally","Center vertically"},(d,w)->change(()->{int index=canvas.theme.elements.indexOf(e);switch(w){case 0:canvas.selected=Domain.duplicate(canvas.theme,e).id;break;case 1:Domain.delete(canvas.theme,e.id);canvas.selected="";break;case 2:e.locked=!e.locked;break;case 3:e.visible=!e.visible;break;case 4:if(index<canvas.theme.elements.size()-1)Collections.swap(canvas.theme.elements,index,index+1);break;case 5:if(index>0)Collections.swap(canvas.theme.elements,index,index-1);break;case 6:e.x=(360-e.w)/2;break;case 7:e.y=(720-e.h)/2;break;}})).show();}
    private LinearLayout sheet(String label){if(sheet!=null)sheet.dismiss();sheet=new Dialog(this);LinearLayout layout=Ui.column(this);layout.setBackground(Ui.rounded(Ui.PANEL,Ui.dp(this,20)));LinearLayout head=Ui.row(this);head.addView(Ui.text(this,label,18,Ui.TEXT),new LinearLayout.LayoutParams(0,-2,1));head.addView(Ui.button(this,"Done",()->sheet.dismiss()));layout.addView(head);ScrollView scroll=new ScrollView(this);LinearLayout content=Ui.column(this);scroll.addView(content);layout.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));sheet.setContentView(layout);Window window=sheet.getWindow();window.setBackgroundDrawableResource(android.R.color.transparent);window.setGravity(Gravity.BOTTOM);window.setLayout(-1,(int)(getResources().getDisplayMetrics().heightPixels*.46));window.setSoftInputMode(WindowManager.LayoutParams.SOFT_INPUT_ADJUST_RESIZE);sheet.show();return content;}
    private void number(LinearLayout parent,String name,float value,java.util.function.Consumer<Float> set){LinearLayout r=Ui.row(this);r.addView(Ui.text(this,name,14,Ui.TEXT),new LinearLayout.LayoutParams(0,Ui.dp(this,48),1));EditText input=new EditText(this);input.setSingleLine();input.setText(String.format(Locale.ROOT,"%.1f",value));input.setTextColor(Ui.TEXT);input.setTextSize(15);input.setInputType(android.text.InputType.TYPE_CLASS_NUMBER|android.text.InputType.TYPE_NUMBER_FLAG_DECIMAL|android.text.InputType.TYPE_NUMBER_FLAG_SIGNED);input.setContentDescription(name);r.addView(input,new LinearLayout.LayoutParams(Ui.dp(this,92),Ui.dp(this,48)));r.addView(Ui.button(this,"Apply",()->{try{float v=Float.parseFloat(input.getText().toString());if(!Float.isFinite(v))throw new IllegalArgumentException();set.accept(v);}catch(Exception e){input.setError("Enter a valid number");}}));parent.addView(r);}
    private void toggle(LinearLayout parent,String name,boolean value,java.util.function.Consumer<Boolean> set){Switch s=new Switch(this);s.setText(name);s.setTextColor(Ui.TEXT);s.setPadding(Ui.dp(this,16),0,Ui.dp(this,16),0);s.setMinHeight(Ui.dp(this,48));s.setChecked(value);s.setOnCheckedChangeListener((b,v)->set.accept(v));parent.addView(s);}
    private void choose(LinearLayout parent,String name,String value,String[] choices,java.util.function.Consumer<String> set){parent.addView(Ui.button(this,name+" · "+value,()->new AlertDialog.Builder(this).setTitle(name).setItems(choices,(d,w)->set.accept(choices[w])).show()));}
    private void color(LinearLayout parent,String name,int current,java.util.function.IntConsumer set){String[] labels={"Pearl","Mint","Amber","Ice","Rose","White","Custom hex"};int[] values={0xffedf3f0,0xffa8e9d1,0xffc9a886,0xff9bcff5,0xffdf9bac,Color.WHITE};parent.addView(Ui.button(this,name,()->new AlertDialog.Builder(this).setTitle(name).setItems(labels,(d,w)->{if(w<values.length)set.accept(values[w]);else input("Color · #RRGGBB",String.format("#%06X",current&0xffffff),v->{try{set.accept(Color.parseColor(v));}catch(Exception e){toast("Use #RRGGBB.");}});}).show()));}
    public void inspector(){Domain.Element e=canvas.selection();if(e==null)return;LinearLayout content=sheet(e.type);if(e.locked){content.addView(Ui.button(this,"Unlock to edit",()->{change(()->e.locked=false);inspector();}));return;}
        number(content,"X",e.x,v->change(()->{e.x=v;Domain.bounds(e);}));number(content,"Y",e.y,v->change(()->{e.y=v;Domain.bounds(e);}));number(content,"Width",e.w,v->change(()->{e.w=v;Domain.bounds(e);}));number(content,"Height",e.h,v->change(()->{e.h=v;Domain.bounds(e);}));number(content,"Rotation",e.rotation,v->change(()->{e.rotation=v;Domain.bounds(e);}));number(content,"Text size",e.size,v->change(()->{e.size=v;Domain.bounds(e);}));number(content,"Opacity",e.opacity,v->change(()->{e.opacity=v;Domain.bounds(e);}));number(content,"Letter spacing",e.spacing,v->change(()->e.spacing=Domain.clamp(v,-2,12)));
        color(content,"Foreground color",e.color,v->change(()->e.color=v));color(content,"Accent color",e.accent,v->change(()->e.accent=v));choose(content,"Font",e.font,new String[]{"sans-serif","sans-serif-thin","sans-serif-condensed","serif","monospace"},v->change(()->e.font=v));toggle(content,"Bold",e.weight>=600,v->change(()->e.weight=v?700:400));choose(content,"Alignment",new String[]{"Left","Center","Right"}[e.align],new String[]{"Left","Center","Right"},v->change(()->e.align=Arrays.asList("Left","Center","Right").indexOf(v)));
        if(e.type.equals("Clock")){choose(content,"Clock family",e.family,Domain.CLOCKS,v->change(()->{e.family=v;if(v.equals("Analog")||v.equals("Split")||v.equals("Vertical"))e.h=Math.max(e.h,200);}));toggle(content,"24-hour time",e.h24,v->change(()->e.h24=v));toggle(content,"Show seconds",e.seconds,v->change(()->e.seconds=v));toggle(content,"Leading zero",e.zero,v->change(()->e.zero=v));}
        if(e.type.equals("Text")){content.addView(Ui.button(this,"Edit text",()->input("Text",e.text,v->change(()->e.text=v))));toggle(content,"Personal text",e.privateContent,v->change(()->e.privateContent=v));}
        if(e.type.equals("Image"))content.addView(Ui.button(this,"Choose image",()->chooseImage(e.id)));
        if(e.type.equals("Shape"))choose(content,"Shape",e.family,new String[]{"Rectangle","Circle","Line"},v->change(()->e.family=v));
        if(e.type.equals("Media"))choose(content,"Artwork",e.treatment,new String[]{"Text only","Compact art","Dimmed art","Monochrome art"},v->change(()->e.treatment=v));
        if(e.type.equals("Notifications")){toggle(content,"Icon-only",e.privateContent,v->change(()->e.privateContent=v));content.addView(Ui.button(this,"Notification access",this::notificationAccess));}
    }
    private void canvasStyle(){LinearLayout content=sheet("Canvas");toggle(content,"Monochrome",canvas.theme.monochrome,v->change(()->canvas.theme.monochrome=v));content.addView(Ui.button(this,"Pure black",()->change(()->{canvas.theme.background=Color.BLACK;canvas.theme.backgroundAsset="";})));color(content,"Preview background",canvas.theme.background,v->change(()->canvas.theme.background=v));content.addView(Ui.button(this,"Preview background image",()->chooseImage("background")));content.addView(Ui.button(this,"Movement safe area",()->{canvas.safeRegion=!canvas.safeRegion;canvas.invalidate();}));}
    private void preview(Domain.Theme theme,String mode){Intent intent=new Intent(this,PreviewActivity.class);intent.putExtra("theme",theme.id);intent.putExtra("mode",mode);startActivity(intent);}
    private void modes(){new AlertDialog.Builder(this).setTitle("Use display").setItems(new String[]{"Preview","Charging · bedside display","Ambient · system screensaver","Lock screen · open manually"},(d,w)->{if(w==2){Intent i=new Intent(Settings.ACTION_DREAM_SETTINGS);if(i.resolveActivity(getPackageManager())==null){toast("Ambient screensaver setup isn't available on this device.");return;}new AlertDialog.Builder(this).setTitle("Enable Ambient").setMessage("Choose AOD in your device's screensaver settings and select when it runs. Availability depends on your device.").setPositiveButton("Open settings",(q,k)->startActivity(i)).setNegativeButton("Cancel",null).show();}else if(w==3)new AlertDialog.Builder(this).setTitle("Manual lock-screen display").setMessage("AOD can remain visible over the lock screen when opened here. It doesn't replace your phone's built-in always-on display or open itself in the background.").setPositiveButton("Open",(q,k)->preview(store.current(isCharging()),"Lock screen")).setNegativeButton("Cancel",null).show();else preview(store.current(w==1),w==0?"Preview":"Charging");}).show();}
    private void notificationAccess(){if(Notifications.granted(this)){toast("Notification access is enabled.");return;}new AlertDialog.Builder(this).setTitle("Notification and media access").setMessage("Allow AOD to display app icons and read active media sessions. Message text stays hidden by default.").setPositiveButton("Open settings",(d,w)->{Intent i=new Intent(Settings.ACTION_NOTIFICATION_LISTENER_SETTINGS);if(i.resolveActivity(getPackageManager())!=null)startActivity(i);else toast("Notification access settings aren't available.");}).setNegativeButton("Later",null).show();}
    public void schedules(){screen="Schedules";shell("Schedules",true);bar.addView(Ui.icon(this,"Add",()->ruleEditor(null)));toggle(root,"Manual design override",store.override,v->{store.override=v;store.save();});Domain.Rule active=store.override?null:Domain.resolve(store.rules,ZonedDateTime.now(),isCharging());root.addView(Ui.text(this,active==null?"Current · "+store.find(store.active).name:"Active · "+active.name+" / "+store.find(active.themeId).name,14,Ui.ACCENT));ScrollView scroll=new ScrollView(this);LinearLayout list=Ui.column(this);scroll.addView(list);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));if(store.rules.isEmpty())list.addView(Ui.text(this,"Create a day, night or charging schedule.",15,Ui.MUTED));for(Domain.Rule r:store.rules){list.addView(Ui.button(this,r.name+" · "+time(r.start)+"–"+time(r.end)+" · "+store.find(r.themeId).name,()->ruleEditor(r)));}root.addView(Ui.text(this,"Higher priority wins. Equal priorities use a stable rule order.",12,Ui.MUTED));}
    private String time(int value){return String.format(Locale.ROOT,"%02d:%02d",value/60,value%60);}
    private void ruleEditor(Domain.Rule original){Domain.Rule r=new Domain.Rule();if(original!=null){r.id=original.id;r.name=original.name;r.themeId=original.themeId;r.start=original.start;r.end=original.end;r.charging=original.charging;r.priority=original.priority;r.days=original.days;}else r.themeId=store.active;LinearLayout c=sheet("Schedule");c.addView(Ui.button(this,"Name · "+r.name,()->input("Rule name",r.name,v->r.name=v)));String[] designs=store.themes.stream().map(t->t.name).toArray(String[]::new);choose(c,"Design",store.find(r.themeId).name,designs,v->{for(Domain.Theme t:store.themes)if(t.name.equals(v)){r.themeId=t.id;break;}});c.addView(Ui.button(this,"Start · "+time(r.start),()->new TimePickerDialog(this,(p,h,m)->r.start=h*60+m,r.start/60,r.start%60,true).show()));c.addView(Ui.button(this,"End · "+time(r.end),()->new TimePickerDialog(this,(p,h,m)->r.end=h*60+m,r.end/60,r.end%60,true).show()));choose(c,"Power",new String[]{"Any","Not charging","Charging"}[r.charging+1],new String[]{"Any","Not charging","Charging"},v->r.charging=Arrays.asList("Any","Not charging","Charging").indexOf(v)-1);number(c,"Priority",r.priority,v->r.priority=(int)Domain.clamp(v,-100,100));String[] days={"Monday","Tuesday","Wednesday","Thursday","Friday","Saturday","Sunday"};for(int i=0;i<7;i++){final int bit=1<<i;toggle(c,days[i],(r.days&bit)!=0,v->{if(v)r.days|=bit;else r.days&=~bit;});}c.addView(Ui.button(this,"Save schedule",()->{if(r.days==0){toast("Choose at least one day.");return;}if(original!=null)store.rules.remove(original);store.rules.add(r);store.save();sheet.dismiss();schedules();}));if(original!=null)c.addView(Ui.button(this,"Delete schedule",()->{store.rules.remove(original);store.save();sheet.dismiss();schedules();}));}
    public void settings(){screen="Settings";shell("Settings",true);ScrollView scroll=new ScrollView(this);LinearLayout c=Ui.column(this);scroll.addView(c);root.addView(scroll,new LinearLayout.LayoutParams(-1,0,1));android.content.SharedPreferences p=store.settings();c.addView(Ui.text(this,"Display",16,Ui.ACCENT));toggle(c,"Burn-in pixel shifting",p.getBoolean("shift",true),v->p.edit().putBoolean("shift",v).commit());toggle(c,"Use device brightness",p.getBoolean("deviceBrightness",false),v->p.edit().putBoolean("deviceBrightness",v).commit());number(c,"Brightness (0–1)",p.getFloat("brightness",.12f),v->p.edit().putFloat("brightness",Domain.clamp(v,.01f,1)).commit());toggle(c,"Dim at night",p.getBoolean("night",true),v->p.edit().putBoolean("night",v).commit());number(c,"Night brightness",p.getFloat("nightBrightness",.02f),v->p.edit().putFloat("nightBrightness",Domain.clamp(v,.01f,.2f)).commit());number(c,"Night start hour",p.getInt("nightStart",22),v->p.edit().putInt("nightStart",(int)Domain.clamp(v,0,23)).commit());number(c,"Night end hour",p.getInt("nightEnd",7),v->p.edit().putInt("nightEnd",(int)Domain.clamp(v,0,23)).commit());
        c.addView(Ui.text(this,"Privacy on ambient displays",16,Ui.ACCENT));toggle(c,"Show media titles",p.getBoolean("media",false),v->p.edit().putBoolean("media",v).commit());toggle(c,"Show calendar titles",p.getBoolean("calendar",false),v->p.edit().putBoolean("calendar",v).commit());toggle(c,"Show personal text",p.getBoolean("personal",false),v->p.edit().putBoolean("personal",v).commit());toggle(c,"Allow public notification previews",p.getBoolean("notificationText",false),v->p.edit().putBoolean("notificationText",v).commit());c.addView(Ui.button(this,Notifications.granted(this)?"Notification access · on":"Notification access · off",this::notificationAccess));Set<String> packages=new TreeSet<>();synchronized(Notifications.items){for(Notifications.Item i:Notifications.items.values())packages.add(i.pkg);}for(String pkg:packages)toggle(c,"Hide "+pkg,p.getBoolean("hide."+pkg,false),v->p.edit().putBoolean("hide."+pkg,v).commit());c.addView(Ui.button(this,checkSelfPermission(android.Manifest.permission.READ_CALENDAR)==PackageManager.PERMISSION_GRANTED?"Calendar access · on":"Calendar access · off",()->requestPermissions(new String[]{android.Manifest.permission.READ_CALENDAR},40)));c.addView(Ui.button(this,"Configure Ambient",this::modes));c.addView(Ui.text(this,"AOD · local-first\nThemes stay on this device. Shared themes include your custom text and images; review them before export.",12,Ui.MUTED));}
    private void chooseImage(String id){pendingImage=id;if(sheet!=null)sheet.dismiss();Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("image/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,10);}
    private void importTheme(){Intent i=new Intent(Intent.ACTION_OPEN_DOCUMENT);i.setType("*/*");i.addCategory(Intent.CATEGORY_OPENABLE);startActivityForResult(i,11);}
    private void exportTheme(Domain.Theme t){new AlertDialog.Builder(this).setTitle("Export "+t.name+"?").setMessage("Custom text and images are included. Notifications, calendar events and media data are never exported.").setPositiveButton("Export",(d,w)->{pendingExport=t.id;Intent i=new Intent(Intent.ACTION_CREATE_DOCUMENT);i.setType("application/json");i.addCategory(Intent.CATEGORY_OPENABLE);i.putExtra(Intent.EXTRA_TITLE,"AOD-"+t.name+".aod.json");startActivityForResult(i,12);}).setNegativeButton("Cancel",null).show();}
    @Override protected void onActivityResult(int request,int result,Intent data){super.onActivityResult(request,result,data);if(result!=RESULT_OK||data==null||data.getData()==null)return;android.net.Uri uri=data.getData();Domain.Theme editing=canvas==null?null:canvas.theme.copy();String selected=pendingImage;String export=pendingExport;io.execute(()->{try{if(request==10){String id;try(InputStream in=getContentResolver().openInputStream(uri)){id=store.importImage(in);}runOnUiThread(()->{if(editing!=null){Domain.Theme before=editing.copy();if(selected.equals("background"))editing.backgroundAsset=id;else for(Domain.Element e:editing.elements)if(e.id.equals(selected))e.asset=id;store.put(editing);if(canvas!=null&&screen.equals("Studio")){history.record(before);canvas.theme=editing;canvas.invalidate();}}});}else if(request==11){Domain.Theme imported;try(InputStream in=getContentResolver().openInputStream(uri)){imported=store.importTheme(in);}runOnUiThread(()->studio(imported));}else if(request==12){String json=store.exportTheme(store.find(export));try(OutputStream out=getContentResolver().openOutputStream(uri,"wt")){out.write(json.getBytes(java.nio.charset.StandardCharsets.UTF_8));}runOnUiThread(()->toast("Theme exported"));}}catch(Exception e){runOnUiThread(()->error(e));}});}
    @Override public void onRequestPermissionsResult(int request,String[] permissions,int[] grants){super.onRequestPermissionsResult(request,permissions,grants);if(canvas!=null){canvas.live.refreshCalendar();canvas.invalidate();}if(screen.equals("Settings"))settings();}
    @Override public void onBackPressed(){if(screen.equals("Home"))super.onBackPressed();else home();}
    @Override protected void onDestroy(){io.shutdown();super.onDestroy();}
}
