package com.tomex.securerenderlab.system;

import android.app.Activity;
import android.app.Presentation;
import android.content.Context;
import android.content.pm.ApplicationInfo;
import android.content.pm.PackageManager;
import android.graphics.Color;
import android.graphics.PixelFormat;
import android.hardware.display.DisplayManager;
import android.hardware.display.VirtualDisplay;
import android.media.Image;
import android.media.ImageReader;
import android.os.Build;
import android.os.Bundle;
import android.os.Handler;
import android.os.Looper;
import android.view.Gravity;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.ScrollView;
import android.widget.TextView;

import java.nio.ByteBuffer;
import java.util.concurrent.atomic.AtomicBoolean;

public final class SystemLabActivity extends Activity {
    private static final String CAPTURE_SECURE_VIDEO_OUTPUT =
            "android.permission.CAPTURE_SECURE_VIDEO_OUTPUT";
    private static final String CAPTURE_VIDEO_OUTPUT =
            "android.permission.CAPTURE_VIDEO_OUTPUT";
    private static final String CAPTURE_BLACKOUT_CONTENT =
            "android.permission.CAPTURE_BLACKOUT_CONTENT";
    private static final String READ_FRAME_BUFFER =
            "android.permission.READ_FRAME_BUFFER";

    private final Handler mainHandler = new Handler(Looper.getMainLooper());
    private TextView capabilityText;
    private TextView secureDisplayText;
    private Presentation activePresentation;
    private VirtualDisplay activeDisplay;
    private ImageReader activeReader;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        ScrollView scroll = new ScrollView(this);
        scroll.setFillViewport(true);
        scroll.setBackgroundColor(Color.rgb(246, 247, 249));

        LinearLayout root = new LinearLayout(this);
        root.setOrientation(LinearLayout.VERTICAL);
        root.setPadding(dp(20), dp(24), dp(20), dp(36));
        scroll.addView(root, new ScrollView.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT));

        root.addView(title("AOSP System Secure Rendering Lab 0.4", 28));
        root.addView(body(
                "This build is intended for an AOSP userdebug system image. It verifies privileged "
                        + "secure-display capability and the SurfaceFlinger secure-capture permission gate using "
                        + "only this lab's synthetic content."));

        root.addView(capabilityCard());
        root.addView(secureDisplayCard());
        root.addView(boundaryCard());

        setContentView(scroll);
        refreshCapabilities();
    }

    private LinearLayout capabilityCard() {
        LinearLayout card = card();
        card.addView(title("Privileged capability state", 18));
        capabilityText = body("Checking…");
        card.addView(capabilityText);
        Button refresh = button("Refresh capability state");
        refresh.setOnClickListener(v -> refreshCapabilities());
        card.addView(refresh);
        return card;
    }

    private LinearLayout secureDisplayCard() {
        LinearLayout card = card();
        card.addView(title("Secure virtual display self-test", 18));
        card.addView(body(
                "Creates a SECURE + OWN_CONTENT_ONLY virtual display and renders a Presentation containing "
                        + "only the text generated by this app. It never mirrors the physical display."));
        secureDisplayText = body("Not run yet.");
        card.addView(secureDisplayText);
        Button run = button("Run privileged secure-display self-test");
        run.setOnClickListener(v -> runSecureDisplaySelfTest());
        card.addView(run);
        return card;
    }

    private LinearLayout boundaryCard() {
        LinearLayout card = card();
        card.addView(title("SurfaceFlinger boundary", 18));
        card.addView(body(
                "CAPTURE_SECURE_VIDEO_OUTPUT controls secure virtual-display creation. "
                        + "CAPTURE_BLACKOUT_CONTENT is a separate SurfaceFlinger gate for requests that ask the "
                        + "compositor to include secure layers. This lab reports that permission but deliberately "
                        + "does not issue a global secure-layer screenshot request."));
        return card;
    }

    private void refreshCapabilities() {
        ApplicationInfo appInfo = getApplicationInfo();
        boolean systemApp = (appInfo.flags & ApplicationInfo.FLAG_SYSTEM) != 0;
        boolean updatedSystem = (appInfo.flags & ApplicationInfo.FLAG_UPDATED_SYSTEM_APP) != 0;
        boolean platformSigned = getPackageManager().checkSignatures(getPackageName(), "android")
                == PackageManager.SIGNATURE_MATCH;

        capabilityText.setText(
                "Build type: " + Build.TYPE
                        + "\nSystem app: " + yesNo(systemApp)
                        + "\nUpdated system app: " + yesNo(updatedSystem)
                        + "\nPlatform signature match: " + yesNo(platformSigned)
                        + "\n\nCAPTURE_SECURE_VIDEO_OUTPUT: " + permissionState(CAPTURE_SECURE_VIDEO_OUTPUT)
                        + "\nCAPTURE_VIDEO_OUTPUT: " + permissionState(CAPTURE_VIDEO_OUTPUT)
                        + "\nCAPTURE_BLACKOUT_CONTENT: " + permissionState(CAPTURE_BLACKOUT_CONTENT)
                        + "\nREAD_FRAME_BUFFER: " + permissionState(READ_FRAME_BUFFER));
    }

    private void runSecureDisplaySelfTest() {
        cleanupSelfTest();
        secureDisplayText.setText("Creating secure own-content-only virtual display…");

        final int width = 480;
        final int height = 270;
        final int density = getResources().getDisplayMetrics().densityDpi;
        final AtomicBoolean finished = new AtomicBoolean(false);

        try {
            activeReader = ImageReader.newInstance(width, height, PixelFormat.RGBA_8888, 3);
            DisplayManager manager = (DisplayManager) getSystemService(Context.DISPLAY_SERVICE);
            activeDisplay = manager.createVirtualDisplay(
                    "SecureRenderingSystemLab",
                    width,
                    height,
                    density,
                    activeReader.getSurface(),
                    DisplayManager.VIRTUAL_DISPLAY_FLAG_OWN_CONTENT_ONLY
                            | DisplayManager.VIRTUAL_DISPLAY_FLAG_SECURE);

            if (activeDisplay == null) {
                secureDisplayText.setText("Secure virtual display returned null.");
                cleanupSelfTest();
                return;
            }

            activeReader.setOnImageAvailableListener(reader -> {
                Image image = reader.acquireLatestImage();
                if (image == null) return;
                try {
                    if (!finished.compareAndSet(false, true)) return;
                    Image.Plane plane = image.getPlanes()[0];
                    ByteBuffer buffer = plane.getBuffer().duplicate();
                    int sampleCount = Math.min(buffer.remaining(), 8192);
                    long checksum = 0;
                    for (int i = 0; i < sampleCount; i++) {
                        checksum = (checksum * 131L + (buffer.get() & 0xff)) & 0x7fffffffL;
                    }
                    final long resultChecksum = checksum;
                    final int resultSampleCount = sampleCount;
                    runOnUiThread(() -> {
                        secureDisplayText.setText(
                                "SUCCESS\nSecure virtual display created.\nSynthetic Presentation produced a frame."
                                        + "\nSample bytes: " + resultSampleCount
                                        + "\nFrame checksum: " + resultChecksum
                                        + "\n\nThis proves privileged secure-output capability for lab-owned content; "
                                        + "it is not a global screenshot bypass.");
                        cleanupSelfTest();
                    });
                } finally {
                    image.close();
                }
            }, mainHandler);

            activePresentation = new Presentation(this, activeDisplay.getDisplay());
            TextView content = new TextView(this);
            content.setText("SYSTEM LAB SECURE OUTPUT 0.4\nSynthetic content only");
            content.setTextSize(28f);
            content.setTextColor(Color.WHITE);
            content.setGravity(Gravity.CENTER);
            content.setBackgroundColor(Color.rgb(52, 42, 92));
            activePresentation.setContentView(content);
            activePresentation.show();

            mainHandler.postDelayed(() -> {
                if (finished.compareAndSet(false, true)) {
                    secureDisplayText.setText(
                            "Secure virtual display was created, but no ImageReader frame arrived before timeout.");
                    cleanupSelfTest();
                }
            }, 2500L);
        } catch (SecurityException e) {
            secureDisplayText.setText("SECURITY EXCEPTION\n" + e.getMessage());
            cleanupSelfTest();
        } catch (Throwable t) {
            secureDisplayText.setText(t.getClass().getSimpleName() + ": " + t.getMessage());
            cleanupSelfTest();
        }
    }

    private String permissionState(String permission) {
        return checkSelfPermission(permission) == PackageManager.PERMISSION_GRANTED
                ? "GRANTED" : "DENIED";
    }

    private String yesNo(boolean value) {
        return value ? "yes" : "no";
    }

    private LinearLayout card() {
        LinearLayout card = new LinearLayout(this);
        card.setOrientation(LinearLayout.VERTICAL);
        card.setPadding(dp(16), dp(16), dp(16), dp(16));
        card.setBackgroundColor(Color.WHITE);
        card.setElevation(dp(2));
        LinearLayout.LayoutParams params = new LinearLayout.LayoutParams(
                ViewGroup.LayoutParams.MATCH_PARENT,
                ViewGroup.LayoutParams.WRAP_CONTENT);
        params.bottomMargin = dp(14);
        card.setLayoutParams(params);
        return card;
    }

    private TextView title(String text, int sp) {
        TextView view = new TextView(this);
        view.setText(text);
        view.setTextSize(sp);
        view.setTextColor(Color.rgb(24, 27, 32));
        view.setPadding(0, 0, 0, dp(8));
        return view;
    }

    private TextView body(String text) {
        TextView view = new TextView(this);
        view.setText(text);
        view.setTextSize(15f);
        view.setTextColor(Color.rgb(65, 72, 82));
        view.setPadding(0, dp(4), 0, dp(10));
        return view;
    }

    private Button button(String text) {
        Button button = new Button(this);
        button.setText(text);
        button.setAllCaps(false);
        button.setMinHeight(dp(52));
        return button;
    }

    private int dp(int value) {
        return Math.round(value * getResources().getDisplayMetrics().density);
    }

    private void cleanupSelfTest() {
        if (activePresentation != null) {
            try { activePresentation.dismiss(); } catch (Throwable ignored) { }
            activePresentation = null;
        }
        if (activeDisplay != null) {
            try { activeDisplay.release(); } catch (Throwable ignored) { }
            activeDisplay = null;
        }
        if (activeReader != null) {
            try { activeReader.close(); } catch (Throwable ignored) { }
            activeReader = null;
        }
    }

    @Override
    protected void onDestroy() {
        cleanupSelfTest();
        super.onDestroy();
    }
}
