org.gradle.jvmargs=-Xmx2g -Dfile.encoding=UTF-8
android.useAndroidX=true
kotlin.code.style=official
android.nonTransitiveRClass=true

HOMIRA_FIREBASE_PROJECT_ID=homira-c5a09
HOMIRA_FIREBASE_APP_ID=1:490956581364:android:a28bad301b008a4ed831a1
HOMIRA_FIREBASE_API_KEY=AIzaSyC9xTq3rqUkgqGsw0Mxuj8woswaIfLzyIY
HOMIRA_FIREBASE_SENDER_ID=490956581364
