package dev.velvet.app

/**
 * Carefully authored offline questions. Distinct questions are curated by intent,
 * not generated at swipe time; additional packs can be reviewed before publishing.
 */
internal object VelvetOfflineLibrary {
    val questions:List<Pair<String,String>> = listOf(
        "Heart to heart" to "What gesture from me makes you feel appreciated without needing words?",
        "Heart to heart" to "When was the last time you felt unexpectedly proud of us?",
        "Heart to heart" to "What kind of reassurance works best when you're overwhelmed?",
        "Heart to heart" to "Which everyday sound or smell makes you think of home with me?",
        "Heart to heart" to "What was the first detail about my personality that caught your attention?",
        "Heart to heart" to "What does a really peaceful day together look like to you?",
        "Heart to heart" to "Which compliment would you like to hear more often?",
        "Heart to heart" to "What part of your day do you most want to share with me?",
        "Heart to heart" to "What's one thing I do that helps you relax?",
        "Heart to heart" to "When do you feel brave enough to be fully yourself around me?",
        "Heart to heart" to "Which shared ritual would you miss most if we were apart?",
        "Heart to heart" to "What emotion is hardest for you to put into words?",
        "Heart to heart" to "What would make our next reunion feel especially meaningful?",
        "Heart to heart" to "What is one quiet moment you'd love to repeat?",
        "Heart to heart" to "What type of affection feels most natural to you?",
        "Heart to heart" to "What part of your childhood would you like me to understand better?",
        "Heart to heart" to "Which recent conversation stayed with you afterward?",
        "Heart to heart" to "What kindness from someone else taught you how to love?",
        "Heart to heart" to "How can I celebrate your successes in a way that feels right?",
        "Heart to heart" to "What makes an apology feel sincere to you?",
        "Heart to heart" to "What's one way we communicate without actually speaking?",
        "Heart to heart" to "What do you hope I always remember about you?",
        "Heart to heart" to "What's a part of your personality you've grown to like more?",
        "Heart to heart" to "What does being chosen every day mean to you?",
        "Heart to heart" to "Which fear feels smaller when we're facing it together?",
        "Heart to heart" to "What would you write on a postcard to our future selves?",
        "Heart to heart" to "What has changed about how you define romance?",
        "Heart to heart" to "What small promise should we make to each other this week?",
        "Heart to heart" to "When does physical closeness matter more than conversation?",
        "Heart to heart" to "What do you wish our friends understood about our relationship?",
        "Heart to heart" to "What kind of support feels helpful when you need some space?",
        "Little laughs" to "If we hosted a game show, what ridiculous prize would we give away?",
        "Little laughs" to "What ordinary household item would be our secret superhero weapon?",
        "Little laughs" to "If our pet could describe us in one sentence, what would it say?",
        "Little laughs" to "What would happen if we traded phone wallpapers for a day?",
        "Little laughs" to "Which snack would cause our silliest disagreement?",
        "Little laughs" to "If we became tour guides, what made-up attraction would we advertise?",
        "Little laughs" to "Who would be more convincing as a detective in a mystery movie?",
        "Little laughs" to "What is the most dramatic way to announce that dinner is ready?",
        "Little laughs" to "If our relationship had a blooper reel, what clip starts it?",
        "Little laughs" to "Which cartoon character would be our chaotic roommate?",
        "Little laughs" to "What fictional gadget would make our life funnier?",
        "Little laughs" to "If we had to invent a holiday, what would people celebrate?",
        "Little laughs" to "Who would accidentally adopt a very unusual pet?",
        "Little laughs" to "What would be our signature karaoke disaster song?",
        "Little laughs" to "Which ridiculous rule would we add to a board game?",
        "Little laughs" to "What would the title of our cooking show be?",
        "Little laughs" to "If we communicated in animal noises for a day, which animals would we choose?",
        "Little laughs" to "What would be the weirdest object in our imaginary museum?",
        "Little laughs" to "Who would win a competition to make the worst pun?",
        "Little laughs" to "If we built a theme park ride, what would it be called?",
        "Little laughs" to "What is one terrible outfit we'd dare each other to wear?",
        "Little laughs" to "What silly superpower would actually be useful at home?",
        "Little laughs" to "If we were in a sitcom, what would the running joke be?",
        "Little laughs" to "What would our secret team mascot look like?",
        "Little laughs" to "Which harmless prank would make us both laugh hardest?",
        "Little laughs" to "If we owned a food truck, what bizarre menu item would be famous?",
        "Little laughs" to "Who would get lost first in a giant furniture store?",
        "Little laughs" to "What dance move would be named after us?",
        "Our future" to "What city would you like us to experience on foot rather than by car?",
        "Our future" to "What language would be fun for us to learn together?",
        "Our future" to "What kind of home library would we build?",
        "Our future" to "Which weekend project should we try with our own hands?",
        "Our future" to "What piece of art would you want hanging in our living room?",
        "Our future" to "How would you want us to spend a rainy Sunday years from now?",
        "Our future" to "What would our ideal celebration of a personal milestone include?",
        "Our future" to "Which recipe should become our signature dish?",
        "Our future" to "What is one financial goal we could work toward as a team?",
        "Our future" to "What outdoor adventure feels just outside our comfort zone?",
        "Our future" to "Which museum or historical site would you visit with me?",
        "Our future" to "What skill would you enjoy teaching me in the future?",
        "Our future" to "What community cause would you like us to support together?",
        "Our future" to "How should we document the ordinary days of our lives?",
        "Our future" to "What kind of garden would you grow if space weren't a problem?",
        "Our future" to "What tradition should we create for welcoming a new year?",
        "Our future" to "Where would you take me to show me your favorite childhood place?",
        "Our future" to "What does a good work-life balance look like for us?",
        "Our future" to "What would you like our guest room to feel like?",
        "Our future" to "Which live performance would be special to experience together?",
        "Our future" to "How would you want to celebrate ten years of knowing each other?",
        "Our future" to "What would we put in a time capsule for ourselves?",
        "Our future" to "Which new hobby deserves a place in our future routine?",
        "Our future" to "If we moved to a new city, how would we make it feel like ours?",
        "Our future" to "What kind of volunteering would you enjoy doing beside me?",
        "Our future" to "What would the perfect morning routine include?",
        "Our future" to "Which corner of our future home should be reserved for creativity?",
        "Our future" to "What adventure would make a meaningful birthday surprise?",
        "Our future" to "What would you want us to remember when life gets very busy?",
        "Sweet & silly" to "If our affection had a weather forecast, what would today's forecast say?",
        "Sweet & silly" to "What tiny object would you keep as a reminder of our first date?",
        "Sweet & silly" to "What handwritten note would you hide in my bag?",
        "Sweet & silly" to "Which flower or plant would represent our personalities together?",
        "Sweet & silly" to "If we invented a couples' handshake, what happens at the end?",
        "Sweet & silly" to "Which animal would make the most adorable mascot for us?",
        "Sweet & silly" to "What flavor of ice cream would you associate with my mood today?",
        "Sweet & silly" to "How would you decorate a cake that tells our story?",
        "Sweet & silly" to "If we could bottle one feeling from our time together, which one?",
        "Sweet & silly" to "What would our matching socks look like?",
        "Sweet & silly" to "What whimsical name would you give our imaginary café?",
        "Sweet & silly" to "Which silly drawing would make you smile on a tough day?",
        "Sweet & silly" to "What three things belong inside our shared treasure box?",
        "Sweet & silly" to "Which playful challenge could we complete in under five minutes?",
        "Sweet & silly" to "If our laugh had a color, which shade would it be?",
        "Sweet & silly" to "How would you describe our relationship using only breakfast foods?",
        "Sweet & silly" to "Which sticker would you design just for our chat?",
        "Sweet & silly" to "What would our fictional band be called?",
        "Sweet & silly" to "Which surprise could fit inside an envelope?",
        "Sweet & silly" to "What costume theme would be funniest for us to wear together?",
        "Sweet & silly" to "If we could rename a constellation after us, what would we call it?",
        "Sweet & silly" to "What harmless dare would you put in a jar for date night?",
        "Sweet & silly" to "Which nursery rhyme would be funniest if we rewrote it about us?",
        "Sweet & silly" to "What would be our secret phrase for 'I need a hug'?",
        "Sweet & silly" to "If we designed a postcard from our relationship, what image is on it?",
        "Sweet & silly" to "What charm would you add to a bracelet that represents me?",
        "Sweet & silly" to "Which two desserts describe our opposite personalities?",
        "Sweet & silly" to "What would our little home flag look like?",
        "Deep talks" to "When do you find it hardest to ask for help?",
        "Deep talks" to "What would a healthy boundary around work messages look like for us?",
        "Deep talks" to "What makes you feel respected during a disagreement?",
        "Deep talks" to "How do you want us to respond if one of us needs time alone?",
        "Deep talks" to "Which family tradition shaped your beliefs about partnership?",
        "Deep talks" to "What does forgiveness mean when trust has been shaken?",
        "Deep talks" to "What kind of honesty is hardest for you to practice?",
        "Deep talks" to "How can we talk about money without making each other defensive?",
        "Deep talks" to "What does a fair division of responsibilities look like to you?",
        "Deep talks" to "When do you need advice and when do you only need listening?",
        "Deep talks" to "What old assumption about relationships have you questioned recently?",
        "Deep talks" to "How should we approach a decision if neither of us wants to compromise?",
        "Deep talks" to "What helps you recognize when stress is affecting your behavior?",
        "Deep talks" to "What would you want us to do after a misunderstanding?",
        "Deep talks" to "How do your friendships help you feel like yourself?",
        "Deep talks" to "What personal goal deserves our mutual encouragement this year?",
        "Deep talks" to "What does trust look like in an ordinary week?",
        "Deep talks" to "Which topic would you like us to discuss without trying to fix anything?",
        "Deep talks" to "How do you know when someone really understands your perspective?",
        "Deep talks" to "What kind of privacy matters most to you in a relationship?",
        "Deep talks" to "What do you need from me when the future feels uncertain?",
        "Deep talks" to "How would we know a disagreement had truly been resolved?",
        "Deep talks" to "What is one belief you inherited that you might change?",
        "Deep talks" to "What does emotional availability look like in daily life?",
        "Deep talks" to "How should we celebrate personal independence while staying connected?",
        "Deep talks" to "What do you wish people asked you instead of assuming?",
        "Deep talks" to "How can we recognize when either of us is overextending ourselves?",
        "Deep talks" to "What would rebuilding a difficult day together involve?",
        "Deep talks" to "What does patience look like during a season of change?",
        "Deep talks" to "What does a meaningful commitment look like beyond big gestures?",
        "Would you rather" to "Would you rather share a hammock by the sea or a bench in the mountains?",
        "Would you rather" to "Would you rather invent a signature dance or a secret greeting?",
        "Would you rather" to "Would you rather build a mini garden or a bookshelf together?",
        "Would you rather" to "Would you rather visit a floating market or a mountain village?",
        "Would you rather" to "Would you rather have a private concert or a private museum tour?",
        "Would you rather" to "Would you rather take spontaneous photos or compose one perfect portrait?",
        "Would you rather" to "Would you rather watch a meteor shower or witness the northern lights?",
        "Would you rather" to "Would you rather spend a weekend in a treehouse or on a houseboat?",
        "Would you rather" to "Would you rather learn to bake bread or make fresh pasta together?",
        "Would you rather" to "Would you rather send each other audio letters or handwritten postcards?",
        "Would you rather" to "Would you rather make a time capsule or create a family cookbook?",
        "Would you rather" to "Would you rather spend a day volunteering or planting a community garden?",
        "Would you rather" to "Would you rather attend a film festival or a live theatre performance?",
        "Would you rather" to "Would you rather create a short documentary or a photo comic?",
        "Would you rather" to "Would you rather take a pottery class or learn wood carving?",
        "Would you rather" to "Would you rather build a giant puzzle or a miniature model village?",
        "Would you rather" to "Would you rather camp beside a waterfall or sleep under a desert sky?",
        "Would you rather" to "Would you rather revisit the same favorite café or try a new one every month?",
        "Would you rather" to "Would you rather host an intimate dinner or a lively board-game night?",
        "Would you rather" to "Would you rather read the same novel or trade your favorite books?",
        "Would you rather" to "Would you rather learn a duet on piano or choreograph a dance?",
        "Would you rather" to "Would you rather take a scenic ferry or a sleeper train?",
        "Would you rather" to "Would you rather name a star together or plant a tree together?",
        "Would you rather" to "Would you rather solve an escape room or navigate a treasure hunt?",
        "Would you rather" to "Would you rather create a mural or make matching clay mugs?",
        "Would you rather" to "Would you rather explore a botanical garden or an aquarium at night?",
        "Would you rather" to "Would you rather design a custom board game or a card deck?",
        "Would you rather" to "Would you rather go stargazing with hot chocolate or watch a thunderstorm from a cabin?"
    )
    private val stop=setOf("the","that","you","your","our","what","which","with","would","could","this","from",
        "should","when","have","together","about","want","like","more","into","were","each","other","we","us","me","how","does")
    private fun words(s:String):Set<String> = Regex("[a-z]{3,}").findAll(s.lowercase())
        .map { it.value }.filter { it !in stop }.toSet()
    /** Fast offline lexical screening, not a claim of guaranteed semantic deduplication. */
    fun isTooSimilar(candidate:String,others:List<String>):Boolean {
        val normal=candidate.lowercase().replace(Regex("[^a-z0-9 ]"),"").trim()
        val a=words(candidate)
        return others.any { old ->
            val b=words(old)
            val other=old.lowercase().replace(Regex("[^a-z0-9 ]"),"").trim()
            normal==other || (a.isNotEmpty() && b.isNotEmpty() &&
                (a intersect b).size.toFloat()/(a union b).size >= .72f)
        }
    }
}
