package com.tomex777.annie

internal object AnnieScriptSpec {
    const val FILE_NAME = "ANNIE_SCRIPTING_SPEC.md"

    fun build(
        project: ScriptProject? = null,
        selectedPath: String? = null,
        selectedSource: String? = null,
    ): String = buildString {
        appendLine("# Annie Scripting Specification")
        appendLine()
        appendLine("Runtime: Annie local JavaScript / QuickJS")
        appendLine("Rendering rule: JavaScript returns structured data; Kotlin/Compose owns all native UI.")
        appendLine("Scripts cannot provide arbitrary Compose code or WebView HTML as a message renderer.")
        appendLine()

        appendLine("## Commands, actions, and sessions")
        appendLine("~~~js")
        appendLine("annie.commands.register({ name: \"hello\", async execute(ctx) { return annie.messages.text(\"Hi\"); } });")
        appendLine("annie.actions.register(\"retry\", async (payload, ctx) => annie.messages.text(\"Retrying\"));")
        appendLine("annie.sessions.register({ name: \"wizard\", async onMessage(ctx) { return annie.messages.text(ctx.text); } });")
        appendLine("ctx.session.start(\"wizard\");")
        appendLine("ctx.session.end();")
        appendLine("~~~")
        appendLine()

        appendLine("## Native services")
        appendLine("- annie.http.request(request) — native HTTP/HTTPS request with status, headers/body and optional browser session.")
        appendLine("- annie.browser.open(spec) — native inline browser message backed by Annie's browser session.")
        appendLine("- await annie.browser.fetch({sessionId, url, method?, headers?, body?}) — run fetch in that live browser page context with its cookies and browser network stack.")
        appendLine("- annie.browser.session(id) / annie.browser.clear(id) — inspect or clear a browser session.")
        appendLine("- annie.storage.get/set(key, value) — arbitrary persistent runtime data scoped to the script.")
        appendLine("- annie.assets.image/audio/uri(id), text(id), json(id) — resolve only manifest-declared package-local assets by logical ID; native UI resolves media URIs.")
        appendLine("- annie.files.readText/writeText/delete/list(path) — private script data files.")
        appendLine("- annie.log.info/warn/error(...) — Script Studio Output logging.")
        appendLine("- annie.services.provide(name, handler) — export only a service declared in the installed package manifest.")
        appendLine("- await annie.services.call(packageId, name, jsonValue) — call an enabled dependency. The caller must declare services.invoke, the exact service permission, and receive the user's grant in Script Studio.")
        appendLine("- Service payloads and results are JSON, capped at 64 KiB, and cannot call another package service while handling a request.")
        appendLine("- The caller manifest pins the provider package version in dependencies and the exact service version/input/output schema IDs in serviceDependencies.")
        appendLine()

        appendLine("## Controlled Android bridge")
        appendLine("- await annie.android.deviceInfo() returns only platform, API level, and locale.")
        appendLine("- Imported packages must declare both the android.device.info capability and android.device.info permission, then receive the user's grant in Script Studio.")
        appendLine("- Android bridge operations are allowlisted individually. Scripts receive plain JSON values, never a Context, Activity, Java object proxy, or general Android access.")
        appendLine()

        appendLine("## Message API")
        appendLine("Registered native message types: ${MessageTypeRegistry.supportedWireNames().joinToString(", ")}.")
        appendLine("~~~js")
        appendLine("return annie.messages.text(\"Hello\");")
        appendLine("return annie.messages.image({ uri, caption: \"Result\" });")
        appendLine("return annie.messages.music({ title, artist, artwork, streamUrl, lyrics });")
        appendLine("return annie.messages.video({ title, uri, thumbnail, width: 1920, height: 1080 });")
        appendLine("return annie.messages.options({ title: \"Choose\", options: [{ id: \"a\", label: \"A\", action: \"pick\" }] });")
        appendLine("return annie.messages.progress({ text: \"Downloading…\", progress: 0.64, state: \"running\" });")
        appendLine("return annie.messages.form({ title: \"Download options\", fields: [{ id: \"quality\", type: \"select\", label: \"Quality\", options: [\"720p\", \"1080p\"] }], submit: { label: \"Download\", action: \"start-download\" } });")
        appendLine("return annie.messages.browser({ url: \"https://example.com\", sessionId: \"source.main\" });")
        appendLine("~~~")
        appendLine("Progress states understood by the native renderer include running/indeterminate, queued, paused, success/completed, failed/error, and cancelled.")
        appendLine("Video cards are compact chat previews; tapping opens Annie's standalone player. Music remains an in-chat player.")
        appendLine("Form messages are temporary conversation interaction. Their submit payload is routed to the owning script action; they are not persistent ENV.")
        appendLine()

        appendLine("## ENV — persistent user configuration")
        appendLine("ENV is declarative configuration and is separate from annie.storage.")
        appendLine("Supported field types: ${ScriptEnvFieldType.entries.joinToString(", ") { it.wireName }}.")
        appendLine("~~~js")
        appendLine("annie.env.define({")
        appendLine("  title: \"My Source\",")
        appendLine("  fields: [")
        appendLine("    { key: \"enabled\", type: \"switch\", label: \"Enabled\", default: true },")
        appendLine("    { key: \"baseUrl\", type: \"text\", label: \"Base URL\" },")
        appendLine("    { key: \"token\", type: \"secret\", label: \"Token\" },")
        appendLine("    { key: \"quality\", type: \"select\", label: \"Preferred quality\", options: [\"720p\", \"1080p\"], default: \"1080p\", scriptWritable: true }")
        appendLine("  ]")
        appendLine("});")
        appendLine("const enabled = await annie.env.get(\"enabled\");")
        appendLine("const token = await annie.env.secret(\"token\");")
        appendLine("await annie.env.set(\"quality\", \"720p\"); // only when scriptWritable is true")
        appendLine("const publicValues = annie.env.values(); // secrets are excluded")
        appendLine("~~~")
        appendLine("Secret ENV values are script-scoped, masked in UI, stored with Android Keystore-backed encryption, excluded from values(), and available only through annie.env.secret(key).")
        appendLine()

        appendLine("## Scheduling")
        appendLine("Schedules persist outside QuickJS. WorkManager recreates the script runtime only when work fires, invokes a registered action, writes its native result into the originating chat, then closes the runtime.")
        appendLine("Recurring schedules must be at least 15 minutes apart and are deferrable/approximate.")
        appendLine("~~~js")
        appendLine("await annie.schedule.create({ id: \"daily-check\", every: \"day\", at: \"19:00\", action: \"check\", payload: {} });")
        appendLine("const schedules = await annie.schedule.list();")
        appendLine("await annie.schedule.disable(\"daily-check\");")
        appendLine("await annie.schedule.enable(\"daily-check\");")
        appendLine("await annie.schedule.cancel(\"daily-check\");")
        appendLine("~~~")
        appendLine()

        appendLine("## Durable tasks")
        appendLine("annie.tasks creates a durable one-shot WorkManager boundary. Annie persists task state, recreates QuickJS for the registered action, delivers the native result to chat, then closes the runtime.")
        appendLine("Task states are queued, running, succeeded, failed, and cancelled. Retry creates a fresh WorkManager attempt for the same stored task.")
        appendLine("Task actions are still bounded script invocations; use native download/media/background services for genuinely long active work rather than an endless JavaScript loop.")
        appendLine("~~~js")
        appendLine("await annie.tasks.start({ id: \"job\", title: \"Processing…\", action: \"run-job\", payload: {} });")
        appendLine("const tasks = await annie.tasks.list();")
        appendLine("await annie.tasks.cancel(\"job\");")
        appendLine("await annie.tasks.retry(\"job\");")
        appendLine("~~~")
        appendLine()

        appendLine("## Browser security")
        appendLine("Browser messages use safe HTTP/HTTPS URLs. Restricted sessions only navigate allowed hosts/subdomains. Browser-session HTTP requests reuse the session's cookies and User-Agent.")
        appendLine()

        appendLine("## Runtime constraints")
        appendLine("- Script execution is bounded; do not build permanently running loops.")
        appendLine("- Keep normal AI/script calls short and structured.")
        appendLine("- Large/long work should be modeled as resumable native tasks when that API is available.")
        appendLine("- Secrets must never be printed to logs or returned in normal exports.")
        appendLine()

        appendLine("## Complete command example")
        appendLine("~~~js")
        appendLine("annie.commands.register({")
        appendLine("  name: \"source\",")
        appendLine("  description: \"Fetch a configured source\",")
        appendLine("  async execute(ctx) {")
        appendLine("    if (!(await annie.env.get(\"enabled\"))) return annie.messages.text(\"Source is disabled\");")
        appendLine("    const baseUrl = await annie.env.get(\"baseUrl\");")
        appendLine("    const response = await annie.http.request({ url: baseUrl + \"/search?q=\" + encodeURIComponent(ctx.text) });")
        appendLine("    return annie.messages.text(response.ok ? response.body : \"Request failed: \" + response.status);")
        appendLine("  }")
        appendLine("});")
        appendLine("~~~")

        if (project != null) {
            appendLine()
            appendLine("## Current project context")
            appendLine("Project: ${project.name}")
            appendLine("Entry: ${project.entryPath}")
            project.files.toSortedMap().forEach { (path, source) ->
                appendLine()
                appendLine("### $path")
                appendLine("~~~js")
                appendLine(if (path == selectedPath && selectedSource != null) selectedSource else source)
                appendLine("~~~")
            }
        }
    }
}
